# Jobs run on separate runners, so each needs to configure their environment
name: Environment setup

runs:
  using: "Composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.5.1
    - name: Install dependencies
      run: npm ci
      shell: bash
    - name: Log success
      if: ${{ success() }}
      run: echo "[ RUNNER ] - successfully installed packages"      
    - name: Log failure
      if: ${{ failure() }}
      run: echo "[ RUNNER ] - failed to install packages" 
