# The purpose of this GitHub action is to have a constant stream of data reporting to the following entities:
# main-agent-test-app-ios: https://staging.onenr.io/07jbMl8KnRy
# main-agent-test-app-android: https://staging.onenr.io/0EjOeXJOOw6

# This is accomplished by triggering npm scripts that execute a suite of tests in parallel
# The tests spin up simulated iOS and Android devices on LambdaTest that are instrumented with the Mobile agent

name: "WDIO - staging: automate iOS and Android tests"

on:
  # enables option for workflow to be manually executed in Github UI
  workflow_dispatch:

  # enables scheduled execution every 30 minutes
  schedule:
    - cron: "*/30 * * * *"

jobs:
  ios-todo-data:
    name: Generate iOS todo data
    runs-on: ubuntu-latest
    env:
      LT_USERNAME: ${{ secrets.APP_EXP_LAMBDA_USERNAME }}
      LT_ACCESSKEY: ${{ secrets.APP_EXP_LAMBDA_ACCESS_KEY }}
      CUSTOM_APP_ID_IOS: "IOSAPP_STAGING"
      ENVIRONMENT: "staging"
      TEST: "./ios-todo.js"
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # pin@v4
      - name: Setup environment
        uses: ./.github/actions/env-setup

      - name: Execute iOS todo tests
        run: for i in {1..2}; do echo "iOS TODO test run $i"; npm run test:wdio-ios; done

      - name: Log success
        if: ${{ success() }}
        run: echo "[ RUNNER ] - successfully executed iOS todo tests"
      - name: Log failure
        if: ${{ failure() || cancelled() }}
        run: echo "[ RUNNER ] - failed to execute iOS todo tests"

      # - name: Notify failure
      #   if: ${{ failure() || cancelled() }}
      #   uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # pin@v2
      #   with:
      #     webhook-type: incoming-webhook
      #     webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     payload: |
      #       blocks:
      #         - type: "header"
      #           text:
      #             type: "plain_text"
      #             text: ":rotating_light: GitHub Workflow Failure"
      #         - type: "divider"
      #         - type: "section"
      #           text:
      #             type: "mrkdwn"
      #             text: ":apple: Failed to generate *main-agent-test-app-iOS* data"
      #           accessory:
      #             type: "button"
      #             text:
      #               type: "plain_text"
      #               text: "View logs"
      #               emoji: true
      #             value: "view_logs"
      #             url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      #             action_id: "button-action"
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  android-todo-data:
    name: Generate Android todo data
    runs-on: ubuntu-latest
    env:
      LT_USERNAME: ${{ secrets.APP_EXP_LAMBDA_USERNAME }}
      LT_ACCESSKEY: ${{ secrets.APP_EXP_LAMBDA_ACCESS_KEY }}
      CUSTOM_APP_ID_ANDROID: "ANDROIDAPP_STAGING"
      ENVIRONMENT: "staging"
      TEST: "./android-todo.js"
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # pin@v4
      - name: Setup environment
        uses: ./.github/actions/env-setup

      - name: Execute Android tests
        run: for i in {1..2}; do echo "Android TODO test run $i"; npm run test:wdio-android; done

      - name: Log success
        if: ${{ success() }}
        run: echo "[ RUNNER ] - successfully executed Android todo tests"

      - name: Log failure
        if: ${{ failure() || cancelled() }}
        run: echo "[ RUNNER ] - failed to execute Android todo tests"
      # - name: Notify failure
      #   if: ${{ failure() || cancelled() }}
      #   uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # pin@v2
      #   with:
      #     webhook-type: incoming-webhook
      #     webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     payload: |
      #       blocks:
      #         - type: "header"
      #           text:
      #             type: "plain_text"
      #             text: ":rotating_light: GitHub Workflow Failure"
      #         - type: "divider"
      #         - type: "section"
      #           text:
      #             type: "mrkdwn"
      #             text: ":robot: Failed to generate *main-agent-test-app-Android* data"
      #           accessory:
      #             type: "button"
      #             text:
      #               type: "plain_text"
      #               text: "View logs"
      #               emoji: true
      #             value: "view_logs"
      #             url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      #             action_id: "button-action"
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  ios-explore-data:
    name: Generate iOS explore data
    needs: [ios-todo-data, android-todo-data]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    env:
      LT_USERNAME: ${{ secrets.APP_EXP_LAMBDA_USERNAME }}
      LT_ACCESSKEY: ${{ secrets.APP_EXP_LAMBDA_ACCESS_KEY }}
      CUSTOM_APP_ID_IOS: "IOSAPP_STAGING"
      ENVIRONMENT: "staging"
      TEST: "./ios-explore.js"
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # pin@v4
      - name: Setup environment
        uses: ./.github/actions/env-setup

      - name: Execute iOS explore tests
        run: for i in {1..2}; do echo "iOS Explore test run $i"; npm run test:wdio-ios; done

      - name: Log success
        if: ${{ success() }}
        run: echo "[ RUNNER ] - successfully executed iOS explore tests"

      - name: Log failure
        if: ${{ failure() || cancelled() }}
        run: echo "[ RUNNER ] - failed to execute iOS explore tests"

  android-explore-data:
    name: Generate Android explore data
    needs: [ios-todo-data, android-todo-data]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    env:
      LT_USERNAME: ${{ secrets.APP_EXP_LAMBDA_USERNAME }}
      LT_ACCESSKEY: ${{ secrets.APP_EXP_LAMBDA_ACCESS_KEY }}
      CUSTOM_APP_ID_ANDROID: "ANDROIDAPP_STAGING"
      ENVIRONMENT: "staging"
      TEST: "./android-explore.js"
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # pin@v4
      - name: Setup environment
        uses: ./.github/actions/env-setup

      - name: Execute Android explore tests
        run: for i in {1..2}; do echo "Android Explore test run $i"; npm run test:wdio-android; done

      - name: Log success
        if: ${{ success() }}
        run: echo "[ RUNNER ] - successfully executed Android explore tests"

      - name: Log failure
        if: ${{ failure() || cancelled() }}
        run: echo "[ RUNNER ] - failed to execute Android explore tests"

  ios-crash-data:
    name: Generate iOS crash data
    needs: [ios-explore-data, android-explore-data]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    env:
      LT_USERNAME: ${{ secrets.APP_EXP_LAMBDA_USERNAME }}
      LT_ACCESSKEY: ${{ secrets.APP_EXP_LAMBDA_ACCESS_KEY }}
      CUSTOM_APP_ID_IOS: "IOSAPP_STAGING"
      ENVIRONMENT: "staging"
      TEST: "./ios-crash.js"
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # pin@v4
      - name: Setup environment
        uses: ./.github/actions/env-setup

      - name: Execute iOS crash tests
        run: for i in {1..2}; do echo "iOS Crash test run $i"; npm run test:wdio-ios; done

      - name: Log success
        if: ${{ success() }}
        run: echo "[ RUNNER ] - successfully executed iOS crash tests"

      - name: Log failure
        if: ${{ failure() || cancelled() }}
        run: echo "[ RUNNER ] - failed to execute iOS crash tests"

  android-crash-data:
    name: Generate Android crash data
    needs: [ios-explore-data, android-explore-data]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    env:
      LT_USERNAME: ${{ secrets.APP_EXP_LAMBDA_USERNAME }}
      LT_ACCESSKEY: ${{ secrets.APP_EXP_LAMBDA_ACCESS_KEY }}
      CUSTOM_APP_ID_ANDROID: "ANDROIDAPP_STAGING"
      ENVIRONMENT: "staging"
      TEST: "./android-crash.js"
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # pin@v4
      - name: Setup environment
        uses: ./.github/actions/env-setup

      - name: Execute Android crash tests
        run: for i in {1..2}; do echo "Android Crash test run $i"; npm run test:wdio-android; done

      - name: Log success
        if: ${{ success() }}
        run: echo "[ RUNNER ] - successfully executed Android crash tests"

      - name: Log failure
        if: ${{ failure() || cancelled() }}
        run: echo "[ RUNNER ] - failed to execute Android crash tests"