name: 'WDIO: automate iOS and Android tests'

on:
  # allows option to trigger workflow manually
  workflow_dispatch:
  
  # TODO: add scheduled execution of workflow once confirmed it's working manually
  # schedule:
  #   - cron: '0 * * * *' # runs hourly

env:
  LT_USERNAME: ${{ secrets.LAMBDA_USERNAME }}
  LT_ACCESSKEY: ${{ secrets.LAMBDA_ACCESS_KEY }}
jobs:
  wdio:
    name: Generate iOS and Android data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run:  npm i
      - name: Generate data
        run: npm run test:wdio-ios
